name: Flickertail Studios
favicon: null
layout_spectrum: 0.88047
typography_spectrum: 0.16533599398098886
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6d5d1'
    - '#00a3b6'
    - '#a19184'
    - '#662c3a'
    - '#c13d54'
  brandStrength: 0.10966269322670996
  lightness: 0.02883177879266441
  saturation: 0.7242311425507069
  rhythmicContrast: 0.8370600836351514
purpose: []
